### PR TITLE
Merge tag 2.7.0

### PR DESCRIPTION
**Pull request by stmuxa**

### CODE REVIEW

**Comment by BenjaminCoquelle** [comment]
The issue we had with long for RIF have been fixed and they use size_t now.
So it seems fine (see tensorocl.cpp).
Reviewing the others changes we made as we also had issue with loading OCL files with their old mechanism so hopefully it is not broken again

**Comment by stmuxa** [comment]
I searched through the project for "long", and did not find anything suspicious.

**Comment by stmuxa** [comment]
We already have it defined at src/include/miopen/env.hpp

**Comment by BenjaminCoquelle** [comment]
ok got it

**Pull request merged**
